name: video-monitor
base: core24
version: git
summary: Remote video streams viewer
description: |
    Shows video from WebRTSP source (like https://snapcraft.io/rtsp-to-webrtsp or https://snapcraft.io/webrtsp-record-streamer) to default output.
    Mostly intended for DIY projects like doorbell cam with optional motion detection.

    **Some hints:**
    * **Config file location:** /var/snap/video-monitor/common/monitor.conf
    * **How to view logs in realtime**: `sudo snap logs video-monitor -f`
    * **How to use it with RTSP source: ** https://github.com/WebRTSP/Monitor#how-to-use-it-with-rtsp-source
    * **How to use it with ONVIF source with optional motion detection:** https://github.com/WebRTSP/Monitor#how-to-use-it-with-onvif-source-with-optional-motion-detection
    * **How to use it with WebRTSP source with optional motion detection:** https://github.com/WebRTSP/Monitor#how-to-use-it-as-webrtsp-client-with-optional-motion-detection-on-server-side
    * **How to use it as WebRTSP server with optional motion detection:** https://github.com/WebRTSP/Monitor#how-to-use-it-as-webrtsp-record-server-with-optional-motion-detection
license: GPL-3.0
grade: stable
confinement: strict
adopt-info: monitor

platforms:
  arm64:

environment:
  GST_DEBUG: 2
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner

layout:
  /etc/glvnd:
    symlink: $SNAP/etc/glvnd
  /usr/share/glvnd:
    symlink: $SNAP/usr/share/glvnd
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri:
    symlink: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gbm:
    symlink: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gbm
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pulseaudio:
    symlink: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pulseaudio

parts:
  monitor:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libmicrohttpd-dev
      - libwebsockets-dev
      - libnice-dev
      - gsoap
      - libgsoap-dev
    stage-packages:
      - libpulse0
      - libegl-mesa0
      - libglu1-mesa
      - libgl1-mesa-dri
      - libglut3.12
      - va-driver-all
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      - gstreamer1.0-nice
      - gstreamer1.0-gl
      - libconfig9
      - libspdlog1.12
      - libmicrohttpd12
      - libwebsockets19t64
      - libwebsockets-evlib-glib
      - libgsoap-2.8.132t64

apps:
  monitor:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas:$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/Monitor
    daemon: simple
    plugs:
      - opengl
      - network-bind
      - network
